-- create authors
CREATE TABLE CMS_AUTHORS (
  id                      NUMERIC(4, 0) NOT NULL PRIMARY KEY,
  first_name              VARCHAR(100)  NOT NULL,
  last_name               VARCHAR(100)  NOT NULL,
  google_plus_author_link VARCHAR(500),
  status                  CHAR(1)       NOT NULL
);
CREATE SEQUENCE CMS_AUTHORS_S START 1 CACHE 1;

-- create authors
CREATE TABLE CMS_LANGUAGES (
  id     NUMERIC(6) PRIMARY KEY NOT NULL,
  code   CHAR(2)                NOT NULL,
  status CHAR(1)                NOT NULL,
  name   VARCHAR(75)            NOT NULL
);
CREATE SEQUENCE CMS_LANGUAGES_S START 1 CACHE 1;
CREATE UNIQUE INDEX CMS_LANGUAGES_IDX ON CMS_LANGUAGES (code);

CREATE TABLE CMS_USERS (
  ID            NUMERIC(10, 0) NOT NULL PRIMARY KEY,
  USERNAME      VARCHAR(100)   NOT NULL,
  PASSWORD_HASH VARCHAR(1024)  NOT NULL,
  STATUS        CHAR(1)        NOT NULL
);
CREATE SEQUENCE CMS_USERS_S START 1 CACHE 1;

CREATE TABLE CMS_ROLES (
  ID        NUMERIC(4, 0) NOT NULL PRIMARY KEY,
  ROLE_CODE VARCHAR(100)  NOT NULL,
  ROLE_NAME VARCHAR(200)  NOT NULL
);
CREATE SEQUENCE CMS_ROLES_S START 1 CACHE 1;

INSERT INTO CMS_ROLES (ID, ROLE_CODE, ROLE_NAME)
VALUES (NEXTVAL('CMS_ROLES_S'), 'ROLE_CWSFE_CMS_ADMIN', 'ROLE_CWSFE_CMS_ADMIN');

CREATE TABLE CMS_USER_ROLES (
  CMS_USER_ID NUMERIC(10, 0) NOT NULL REFERENCES CMS_USERS (ID),
  ROLE_ID     NUMERIC(4, 0)  NOT NULL REFERENCES CMS_ROLES (ID),
  PRIMARY KEY (CMS_USER_ID, ROLE_ID)
);

CREATE TABLE CMS_GLOBAL_PARAMS (
  ID            NUMERIC(4, 0) NOT NULL PRIMARY KEY,
  CODE          VARCHAR(200)  NOT NULL UNIQUE,
  DEFAULT_VALUE VARCHAR(400)  NOT NULL,
  VALUE         VARCHAR(400)  NOT NULL,
  DESCRIPTION   VARCHAR(1000) NOT NULL
);
CREATE SEQUENCE CMS_GLOBAL_PARAMS_S START 1 CACHE 1;
INSERT INTO CMS_GLOBAL_PARAMS (ID, CODE, DEFAULT_VALUE, VALUE, DESCRIPTION) VALUES (
  nextval('CMS_GLOBAL_PARAMS_S'), 'CWSFE_CMS_VERSION', '1.0', '1.0', 'CWSFE CMS VERSION'
);
INSERT INTO CMS_GLOBAL_PARAMS (ID, CODE, DEFAULT_VALUE, VALUE, DESCRIPTION) VALUES (
  nextval('CMS_GLOBAL_PARAMS_S'), 'MAIN_SITE', 'http://cwsfe.eu', 'http://cwsfe.eu',
  'MAIN WEBSITE OUTSIDE OF CWSFE CMS WEBSITE'
);
INSERT INTO CMS_GLOBAL_PARAMS (ID, CODE, DEFAULT_VALUE, VALUE, DESCRIPTION) VALUES (
  nextval('CMS_GLOBAL_PARAMS_S'), 'CWSFE_CMS_IS_CONFIGURED', 'N', 'N', 'IS CWSFE CMS CONFIGURED: "Y"es or "N"o'
);
