CREATE TABLE NEWSLETTER_MAIL_GROUPS (
  ID          NUMERIC(6, 0) NOT NULL PRIMARY KEY,
  LANGUAGE_ID NUMERIC(3, 0) NOT NULL REFERENCES cms_languages (id),
  NAME        VARCHAR(100)  NOT NULL,
  STATUS      CHAR(1)       NOT NULL
);
CREATE SEQUENCE NEWSLETTER_MAIL_GROUPS_S START 1 CACHE 1;

CREATE TABLE NEWSLETTER_MAIL_ADDRESSES (
  ID                  NUMERIC(6, 0) NOT NULL PRIMARY KEY,
  MAIL_GROUP_ID       NUMERIC(6, 0) NOT NULL REFERENCES NEWSLETTER_MAIL_GROUPS (ID),
  CONFIRM_STRING      VARCHAR(36)   NOT NULL UNIQUE,
  UN_SUBSCRIBE_STRING VARCHAR(36)   NOT NULL UNIQUE,
  EMAIL               VARCHAR(300)  NOT NULL,
  STATUS              CHAR(1)       NOT NULL,
  UNIQUE (MAIL_GROUP_ID, EMAIL)
);
CREATE SEQUENCE NEWSLETTER_MAIL_ADDRESSES_S START 1 CACHE 1;
CREATE INDEX NEWSLETTER_MAIL_ADDRESSES_MAIL_GROUP_ID_INDEX ON NEWSLETTER_MAIL_ADDRESSES (MAIL_GROUP_ID);
CREATE INDEX NEWSLETTER_MAIL_ADDRESSES_CONFIRM_STRING_INDEX ON NEWSLETTER_MAIL_ADDRESSES (CONFIRM_STRING);
CREATE INDEX NEWSLETTER_MAIL_ADDRESSES_UN_SUBSCRIBE_STRING_INDEX ON NEWSLETTER_MAIL_ADDRESSES (UN_SUBSCRIBE_STRING);

CREATE TABLE NEWSLETTER_TEMPLATES (
  ID          NUMERIC(4, 0) NOT NULL PRIMARY KEY,
  LANGUAGE_ID NUMERIC(3, 0) NOT NULL REFERENCES cms_languages (id),
  NAME        VARCHAR(100)  NOT NULL,
  STATUS      CHAR(1)       NOT NULL,
  SUBJECT     VARCHAR(300)  NOT NULL,
  CONTENT     TEXT          NOT NULL DEFAULT ''
);
CREATE SEQUENCE NEWSLETTER_TEMPLATES_S START 1 CACHE 1;

CREATE TABLE NEWSLETTER_MAIL (
  ID                 NUMERIC(6, 0)                                        NOT NULL PRIMARY KEY,
  RECIPIENT_GROUP_ID NUMERIC(6, 0) REFERENCES NEWSLETTER_MAIL_GROUPS (ID) NOT NULL,
  NAME               VARCHAR(100)                                         NOT NULL,
  SUBJECT            VARCHAR(300)                                         NOT NULL,
  MAIL_CONTENT       TEXT                                                 NOT NULL DEFAULT '',
  STATUS             CHAR(1)                                              NOT NULL
);
CREATE SEQUENCE NEWSLETTER_MAIL_S START 1 CACHE 1;

CREATE TABLE NEWSLETTER_DISPATCHED_MAILS (
  ID                 NUMERIC(6, 0)                                 NOT NULL PRIMARY KEY,
  NEWSLETTER_MAIL_ID NUMERIC(6, 0) REFERENCES NEWSLETTER_MAIL (ID) NOT NULL,
  EMAIL              VARCHAR(300)                                  NOT NULL,
  ERROR              VARCHAR(500),
  STATUS             CHAR(1)                                       NOT NULL
);
CREATE SEQUENCE NEWSLETTER_DISPATCHED_MAILS_S START 1 CACHE 1;
